version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_normalizacion
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: datasets_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_network

  app:
    build: .
    container_name: app_normalizacion
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secretpassword
      - DB_NAME=datasets_db
    volumes:
      - .:/app
    networks:
      - db_network
    command: tail -f /dev/null 

volumes:
  pgdata:

networks:
  db_network:
    driver: bridge